config/routes.rb
Rails.application.routes.draw do
    get '/', to: 'static_pages#index'
    get '/home', to: 'static_pages#home'
    get '/team', to: 'static_pages#team'
    get '/contact', to: 'static_pages#contact'
    get '/welcome/:name', to: 'static_pages#welcome'
    get '/gossip/:number', to: 'static_pages#gossip'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user



end

app/models/user.rb
class User < ApplicationRecord
	has_many :gossips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController


	def index
		
	end

	def home
		@gossips = Gossip.all
	end

	def contact
		
	end

	def team
		
	end

	def welcome
		@gossips = Gossip.all
	end

	def gossip
		@gossip = Gossip.find(params[:number])
	end

	def author
		@author = User.all
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </head>

  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">the_Gossip_Project</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <div class="nav-link" >
              <%= link_to "Home", home_path %>
            </div>
          </li>
          <li class="nav-item">
            <div class="nav-link" >
              <%= link_to "Team", team_path %>
            </div>
          </li>
          <li class="nav-item">
            <div class="nav-link" >
              <%= link_to "Contact", contact_path %>
            </div>
          </li>
        </ul>
      </div>
    </nav>
  </header>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/contact.html.erb
<html>
  <head>
    <title>The Gossip Project</title>
  </head>

  <body>
    <h1> Contact</h1>
    <p>Dan Bertrand - Berlin</p>
    <p>You can email me at any time : <a href="mailto:dan.bertrand.hs@gmail.com">Send me an email</a></p>

  
  </body>
</html>

app/views/static_pages/gossip.html.erb
<html>
  <head>
    <title>The Gossip Project</title>
  </head>
  <body>


    <h1> This is the special page for the Gossip n°<%= @gossip.id %></h1>
    </br>
    </br>
    </br>
    Author :<%= @gossip.author%></br>
    Title:<%= @gossip.title%></br>
    Content :<%= @gossip.content%></br>



  </body>


</html>

app/views/static_pages/home.html.erb
<html>
  <head>
    <title>The Gossip Project</title>
  </head>
  <body>
    <h1> Welcome to the Home page of "my gossip website" ! The gossip list is coming soon.</h1>



   

    <h2> You will be soon able to create a new gossip by clincking the link below</h2>


   
    <h2> Here is all the Gossip created previously</h2> 
    <br/>  
    <br/>  




    <% @gossips.each do |gossip| %>
      
       Gossip n°
       <%= gossip.id %><br/>  
       Author: <%= gossip.author %><br/>
       Title: <%= gossip.title %><br/>
       Content: <%= gossip.content %><br/>
       Creation date : <%= gossip.created_at %>





  
       <br/>
       <br/>

    <% end %>

  </body>
</html>

app/views/static_pages/team.html.erb
<html>
  <head>
    <title>The Gossip Project</title>
  </head>

  <body>
    <h1> Welcome to the team page</h1>

    <p>I have been woring alone for this project. Not easy. Happy to do pair programming the next time.</p>

  
  </body>
</html>

app/views/static_pages/welcome.html.erb
<html>
  <head>
    <title>The Gossip Project</title>
  </head>


  <body>
    
    <h2>Welcome <%= params["name"].capitalize %> !</h2>
    
    <p>Here you can find our brand new Gossip website. Let us know what you think about it ;)</p>
    

    <p>Below, you can check on all the Gossips already created</p>


    <% @gossips.each do |gossip| %>
    	
       Gossip n°
       <%= gossip.id %><br/>  
       Author: <%= gossip.author %><br/>
       Title: <%= gossip.title %><br/>
       <br/>
       <br/>

    <% end %>


  </body>
</html>